package net.runelite.client.plugins.autovorkath;

public enum State
{
    DODGE_BOMB,
    ACID_WALK,
    ATTACK_VORKATH,
    SWITCH_DIAMOND,
    SWITCH_RUBY,
    KILL_SPAWN,
    DRINK_ANTIFIRE,
    DRINK_ANTIVENOM,
    DRINK_BOOST,
    EAT_FOOD,
    LOOT_VORKATH,
    POKE_VORKATH,
    DISTANCE_CHECK,
    USE_POOL,
    TELEPORT_FEROX_ENCLAVE,
    TELEPORT_MOONCLAN,
    USE_BANK_MOONCLAN,
    USE_BANK_FEROX_ENCLAVE,
    USE_BOAT,
    USE_OBSTACLE,
    LEAVE_MOONCLAN,
    TOGGLE_RUN,
    TICK_DELAY,
    DEFAULT
}
